### ISSUE TITLE
Storing events into mongo db throws an exception if used with MongoDB.Driver 2.5.0

### ISSUE THREAD

**Issue by csi-michaelsagalovich** [MementoFX/MementoFX.Persistence.MongoDB#1]
See:

https://github.com/MementoFX/MementoFX.Persistence.MongoDB/blob/b10e46b39d008a19cdd1c8c21699748b8f855822/src/MementoFX.Persistence.MongoDB/MongoDbEventStore.cs#L90

and 

https://github.com/mongodb/mongo-csharp-driver/blob/6c0bb11aa0efc250f5cd374a536043d56361fa9b/src/MongoDB.Driver/IMongoCollection.cs#L595

In MongoDB v2.5.0 an overload for method InsertOne was added into IMongoCollection, which makes mongoCollectionType.GetMethod("InsertOne"); fail with AmbiguousMatchException (Ambiguous match found.)

A quick solution would be to add a high limit for supported version of MongoDB Driver into MementoFX.Persistence.MongoDB NuGet package - 2.4.4. 

A permanent solution is to rewrite the failing code to loop through all InsertOne methods in IMongoCollection and pick the required one.

**Comment by enosrecanati** [comment]
Thank you for point us to the problem, and to have shared back your fix.
